/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed-variant": "#004a77",
        "primary-fixed": "#cfe5ff",
        "error-container": "#93000a",
        "background": "#131313",
        "tertiary": "#c8c6c5",
        "secondary-container": "#ffbf00",
        "on-background": "#e2e2e2",
        "surface-container": "#1f1f1f",
        "on-primary": "#003354",
        "inverse-surface": "#e2e2e2",
        "surface-variant": "#353535",
        "on-secondary-fixed": "#261a00",
        "tertiary-fixed": "#e5e2e1",
        "surface-dim": "#131313",
        "tertiary-container": "#9e9c9c",
        "surface-container-highest": "#353535",
        "primary-fixed-dim": "#98cbff",
        "error": "#ffb4ab",
        "surface": "#131313",
        "outline": "#88919d",
        "primary": "#98cbff",
        "on-primary-container": "#00375a",
        "on-secondary": "#402d00",
        "secondary-fixed": "#ffdfa0",
        "on-tertiary": "#313030",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed-variant": "#5c4300",
        "secondary-fixed-dim": "#fbbc00",
        "on-tertiary-fixed": "#1c1b1b",
        "on-primary-fixed": "#001d33",
        "on-secondary-container": "#6d5000",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#bec7d4",
        "inverse-on-surface": "#303030",
        "on-error-container": "#ffdad6",
        "primary-container": "#00a3ff",
        "outline-variant": "#3f4852",
        "on-error": "#690005",
        "surface-container-low": "#1b1b1b",
        "surface-bright": "#393939",
        "on-surface": "#e2e2e2",
        "secondary": "#ffe2ab",
        "on-tertiary-container": "#343434",
        "on-tertiary-fixed-variant": "#474646",
        "surface-tint": "#98cbff",
        "inverse-primary": "#00629d",
        "success": "#22C55E",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        base: "4px",
        "margin-mobile": "16px",
        gutter: "16px",
        "stack-gap": "8px",
        "sidebar-width": "64px",
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "30px", fontWeight: "700" }],
        "data-mono": ["14px", { lineHeight: "18px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
